# Base URL used when generating links to your pages
baseURL = "https://lizfer.social"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Luiz Ferreira - lizfer.social"
author = "Luiz Ferreira"
copyright = "Copyright © 2025, Luiz Ferreira - lizfer.social."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/blog/:slug/"
  tags = "/tags/:slug/"

[params]
  # Site description for SEO
  description = "Luiz Ferreira's personal blog about cloud architecture, DevOps practices, and tech career insights"

  # Favicon path
  favicon = "images/lizfer.png"

  # Image for social sharing
  images = ["images/lizfer.png"]

  # Title for Open Graph
  title = "Luiz Ferreira - Cloud Solutions Architect"

  # Hide "Made with" line
  hideMadeWithLine = true

  # Custom date format
  dateFormat = "2 January, 2006"

# Configure markup highlighter
[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

# Menu configuration
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 20

# Social links
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/l1zfer"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/lizfer/"

# Pagination settings
paginate = 10